
package webService.correios.atende;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-01T20:04:39.866-04:00
 * Generated source version: 3.2.1
 * 
 */
public final class AtendeCliente_AtendeClientePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClienteService");

    private AtendeCliente_AtendeClientePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AtendeClienteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AtendeClienteService ss = new AtendeClienteService(wsdlURL, SERVICE_NAME);
        AtendeCliente port = ss.getAtendeClientePort();  
        
        {
        System.out.println("Invoking buscaServicosAdicionaisAtivos...");
        java.lang.String _buscaServicosAdicionaisAtivos_usuario = "";
        java.lang.String _buscaServicosAdicionaisAtivos_senha = "";
        try {
            java.util.List<webService.correios.atende.ServicoAdicionalXML> _buscaServicosAdicionaisAtivos__return = port.buscaServicosAdicionaisAtivos(_buscaServicosAdicionaisAtivos_usuario, _buscaServicosAdicionaisAtivos_senha);
            System.out.println("buscaServicosAdicionaisAtivos.result=" + _buscaServicosAdicionaisAtivos__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fechaPlp...");
        java.lang.String _fechaPlp_xml = "";
        java.lang.Long _fechaPlp_idPlpCliente = null;
        java.lang.String _fechaPlp_cartaoPostagem = "";
        java.lang.String _fechaPlp_faixaEtiquetas = "";
        java.lang.String _fechaPlp_usuario = "";
        java.lang.String _fechaPlp_senha = "";
        try {
            java.lang.Long _fechaPlp__return = port.fechaPlp(_fechaPlp_xml, _fechaPlp_idPlpCliente, _fechaPlp_cartaoPostagem, _fechaPlp_faixaEtiquetas, _fechaPlp_usuario, _fechaPlp_senha);
            System.out.println("fechaPlp.result=" + _fechaPlp__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaSRO...");
        java.util.List<java.lang.String> _consultaSRO_listaObjetos = null;
        java.lang.String _consultaSRO_tipoConsulta = "";
        java.lang.String _consultaSRO_tipoResultado = "";
        java.lang.String _consultaSRO_usuarioSro = "";
        java.lang.String _consultaSRO_senhaSro = "";
        try {
            java.lang.String _consultaSRO__return = port.consultaSRO(_consultaSRO_listaObjetos, _consultaSRO_tipoConsulta, _consultaSRO_tipoResultado, _consultaSRO_usuarioSro, _consultaSRO_senhaSro);
            System.out.println("consultaSRO.result=" + _consultaSRO__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validaPlp...");
        long _validaPlp_cliente = 0;
        java.lang.String _validaPlp_numero = "";
        long _validaPlp_diretoria = 0;
        java.lang.String _validaPlp_cartao = "";
        java.lang.String _validaPlp_unidadePostagem = "";
        java.lang.Long _validaPlp_servico = null;
        java.util.List<java.lang.String> _validaPlp_servicosAdicionais = null;
        java.lang.String _validaPlp_usuario = "";
        java.lang.String _validaPlp_senha = "";
        try {
            boolean _validaPlp__return = port.validaPlp(_validaPlp_cliente, _validaPlp_numero, _validaPlp_diretoria, _validaPlp_cartao, _validaPlp_unidadePostagem, _validaPlp_servico, _validaPlp_servicosAdicionais, _validaPlp_usuario, _validaPlp_senha);
            System.out.println("validaPlp.result=" + _validaPlp__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking calculaTarifaServico...");
        java.lang.String _calculaTarifaServico_codAdministrativo = "";
        java.lang.String _calculaTarifaServico_usuario = "";
        java.lang.String _calculaTarifaServico_senha = "";
        java.lang.String _calculaTarifaServico_codServico = "";
        java.lang.String _calculaTarifaServico_cepOrigem = "";
        java.lang.String _calculaTarifaServico_cepDestino = "";
        java.lang.String _calculaTarifaServico_peso = "";
        java.lang.Integer _calculaTarifaServico_codFormato = null;
        java.lang.Double _calculaTarifaServico_comprimento = null;
        java.lang.Double _calculaTarifaServico_altura = null;
        java.lang.Double _calculaTarifaServico_largura = null;
        java.lang.Double _calculaTarifaServico_diametro = null;
        java.lang.String _calculaTarifaServico_codMaoPropria = "";
        java.lang.Double _calculaTarifaServico_valorDeclarado = null;
        java.lang.String _calculaTarifaServico_codAvisoRecebimento = "";
        try {
            java.lang.String _calculaTarifaServico__return = port.calculaTarifaServico(_calculaTarifaServico_codAdministrativo, _calculaTarifaServico_usuario, _calculaTarifaServico_senha, _calculaTarifaServico_codServico, _calculaTarifaServico_cepOrigem, _calculaTarifaServico_cepDestino, _calculaTarifaServico_peso, _calculaTarifaServico_codFormato, _calculaTarifaServico_comprimento, _calculaTarifaServico_altura, _calculaTarifaServico_largura, _calculaTarifaServico_diametro, _calculaTarifaServico_codMaoPropria, _calculaTarifaServico_valorDeclarado, _calculaTarifaServico_codAvisoRecebimento);
            System.out.println("calculaTarifaServico.result=" + _calculaTarifaServico__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificaSeTodosObjetosCancelados...");
        java.util.List<webService.correios.atende.ObjetoPostal> _verificaSeTodosObjetosCancelados_arg0 = null;
        try {
            boolean _verificaSeTodosObjetosCancelados__return = port.verificaSeTodosObjetosCancelados(_verificaSeTodosObjetosCancelados_arg0);
            System.out.println("verificaSeTodosObjetosCancelados.result=" + _verificaSeTodosObjetosCancelados__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelarObjeto...");
        java.lang.Long _cancelarObjeto_idPlp = null;
        java.lang.String _cancelarObjeto_numeroEtiqueta = "";
        java.lang.String _cancelarObjeto_usuario = "";
        java.lang.String _cancelarObjeto_senha = "";
        try {
            java.lang.Boolean _cancelarObjeto__return = port.cancelarObjeto(_cancelarObjeto_idPlp, _cancelarObjeto_numeroEtiqueta, _cancelarObjeto_usuario, _cancelarObjeto_senha);
            System.out.println("cancelarObjeto.result=" + _cancelarObjeto__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking atualizaPagamentoNaEntrega...");
        java.lang.String _atualizaPagamentoNaEntrega_usuario = "";
        java.lang.String _atualizaPagamentoNaEntrega_senha = "";
        try {
            java.lang.String _atualizaPagamentoNaEntrega__return = port.atualizaPagamentoNaEntrega(_atualizaPagamentoNaEntrega_usuario, _atualizaPagamentoNaEntrega_senha);
            System.out.println("atualizaPagamentoNaEntrega.result=" + _atualizaPagamentoNaEntrega__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterClienteAtualizacao...");
        java.lang.String _obterClienteAtualizacao_cnpjCliente = "";
        java.lang.String _obterClienteAtualizacao_usuario = "";
        java.lang.String _obterClienteAtualizacao_senha = "";
        try {
            javax.xml.datatype.XMLGregorianCalendar _obterClienteAtualizacao__return = port.obterClienteAtualizacao(_obterClienteAtualizacao_cnpjCliente, _obterClienteAtualizacao_usuario, _obterClienteAtualizacao_senha);
            System.out.println("obterClienteAtualizacao.result=" + _obterClienteAtualizacao__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificaDisponibilidadeServico...");
        java.lang.Integer _verificaDisponibilidadeServico_codAdministrativo = null;
        java.lang.String _verificaDisponibilidadeServico_numeroServico = "";
        java.lang.String _verificaDisponibilidadeServico_cepOrigem = "";
        java.lang.String _verificaDisponibilidadeServico_cepDestino = "";
        java.lang.String _verificaDisponibilidadeServico_usuario = "";
        java.lang.String _verificaDisponibilidadeServico_senha = "";
        try {
            boolean _verificaDisponibilidadeServico__return = port.verificaDisponibilidadeServico(_verificaDisponibilidadeServico_codAdministrativo, _verificaDisponibilidadeServico_numeroServico, _verificaDisponibilidadeServico_cepOrigem, _verificaDisponibilidadeServico_cepDestino, _verificaDisponibilidadeServico_usuario, _verificaDisponibilidadeServico_senha);
            System.out.println("verificaDisponibilidadeServico.result=" + _verificaDisponibilidadeServico__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fechaPlpVariosServicos...");
        java.lang.String _fechaPlpVariosServicos_xml = "";
        java.lang.Long _fechaPlpVariosServicos_idPlpCliente = null;
        java.lang.String _fechaPlpVariosServicos_cartaoPostagem = "";
        java.util.List<java.lang.String> _fechaPlpVariosServicos_listaEtiquetas = null;
        java.lang.String _fechaPlpVariosServicos_usuario = "";
        java.lang.String _fechaPlpVariosServicos_senha = "";
        try {
            java.lang.Long _fechaPlpVariosServicos__return = port.fechaPlpVariosServicos(_fechaPlpVariosServicos_xml, _fechaPlpVariosServicos_idPlpCliente, _fechaPlpVariosServicos_cartaoPostagem, _fechaPlpVariosServicos_listaEtiquetas, _fechaPlpVariosServicos_usuario, _fechaPlpVariosServicos_senha);
            System.out.println("fechaPlpVariosServicos.result=" + _fechaPlpVariosServicos__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking geraDigitoVerificadorEtiquetas...");
        java.util.List<java.lang.String> _geraDigitoVerificadorEtiquetas_etiquetas = null;
        java.lang.String _geraDigitoVerificadorEtiquetas_usuario = "";
        java.lang.String _geraDigitoVerificadorEtiquetas_senha = "";
        try {
            java.util.List<java.lang.Integer> _geraDigitoVerificadorEtiquetas__return = port.geraDigitoVerificadorEtiquetas(_geraDigitoVerificadorEtiquetas_etiquetas, _geraDigitoVerificadorEtiquetas_usuario, _geraDigitoVerificadorEtiquetas_senha);
            System.out.println("geraDigitoVerificadorEtiquetas.result=" + _geraDigitoVerificadorEtiquetas__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterEmbalagemLRS...");
        try {
            java.util.List<webService.correios.atende.EmbalagemLRSMaster> _obterEmbalagemLRS__return = port.obterEmbalagemLRS();
            System.out.println("obterEmbalagemLRS.result=" + _obterEmbalagemLRS__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validaEtiquetaPLP...");
        java.lang.String _validaEtiquetaPLP_numeroEtiqueta = "";
        java.lang.Long _validaEtiquetaPLP_idPlp = null;
        java.lang.String _validaEtiquetaPLP_usuario = "";
        java.lang.String _validaEtiquetaPLP_senha = "";
        try {
            boolean _validaEtiquetaPLP__return = port.validaEtiquetaPLP(_validaEtiquetaPLP_numeroEtiqueta, _validaEtiquetaPLP_idPlp, _validaEtiquetaPLP_usuario, _validaEtiquetaPLP_senha);
            System.out.println("validaEtiquetaPLP.result=" + _validaEtiquetaPLP__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaServicosValorDeclarado...");
        java.lang.String _buscaServicosValorDeclarado_usuario = "";
        java.lang.String _buscaServicosValorDeclarado_senha = "";
        try {
            java.util.List<java.lang.String> _buscaServicosValorDeclarado__return = port.buscaServicosValorDeclarado(_buscaServicosValorDeclarado_usuario, _buscaServicosValorDeclarado_senha);
            System.out.println("buscaServicosValorDeclarado.result=" + _buscaServicosValorDeclarado__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaCEP...");
        java.lang.String _consultaCEP_cep = "";
        try {
            webService.correios.atende.EnderecoERP _consultaCEP__return = port.consultaCEP(_consultaCEP_cep);
            System.out.println("consultaCEP.result=" + _consultaCEP__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking integrarUsuarioScol...");
        java.lang.Integer _integrarUsuarioScol_codAdministrativo = null;
        java.lang.String _integrarUsuarioScol_usuario = "";
        java.lang.String _integrarUsuarioScol_senha = "";
        try {
            java.lang.Boolean _integrarUsuarioScol__return = port.integrarUsuarioScol(_integrarUsuarioScol_codAdministrativo, _integrarUsuarioScol_usuario, _integrarUsuarioScol_senha);
            System.out.println("integrarUsuarioScol.result=" + _integrarUsuarioScol__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking atualizaRemessaAgrupada...");
        java.lang.String _atualizaRemessaAgrupada_usuario = "";
        java.lang.String _atualizaRemessaAgrupada_senha = "";
        try {
            java.lang.String _atualizaRemessaAgrupada__return = port.atualizaRemessaAgrupada(_atualizaRemessaAgrupada_usuario, _atualizaRemessaAgrupada_senha);
            System.out.println("atualizaRemessaAgrupada.result=" + _atualizaRemessaAgrupada__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaPLP...");
        java.lang.Long _solicitaPLP_idPlpMaster = null;
        java.lang.String _solicitaPLP_numEtiqueta = "";
        java.lang.String _solicitaPLP_usuario = "";
        java.lang.String _solicitaPLP_senha = "";
        try {
            java.lang.String _solicitaPLP__return = port.solicitaPLP(_solicitaPLP_idPlpMaster, _solicitaPLP_numEtiqueta, _solicitaPLP_usuario, _solicitaPLP_senha);
            System.out.println("solicitaPLP.result=" + _solicitaPLP__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getStatusCartaoPostagem...");
        java.lang.String _getStatusCartaoPostagem_numeroCartaoPostagem = "";
        java.lang.String _getStatusCartaoPostagem_usuario = "";
        java.lang.String _getStatusCartaoPostagem_senha = "";
        try {
            webService.correios.atende.StatusCartao _getStatusCartaoPostagem__return = port.getStatusCartaoPostagem(_getStatusCartaoPostagem_numeroCartaoPostagem, _getStatusCartaoPostagem_usuario, _getStatusCartaoPostagem_senha);
            System.out.println("getStatusCartaoPostagem.result=" + _getStatusCartaoPostagem__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaTarifaVale...");
        java.lang.String _buscaTarifaVale_codAdministrativo = "";
        java.lang.String _buscaTarifaVale_usuario = "";
        java.lang.String _buscaTarifaVale_senha = "";
        java.lang.String _buscaTarifaVale_codServico = "";
        java.lang.String _buscaTarifaVale_cepOrigem = "";
        java.lang.String _buscaTarifaVale_cepDestino = "";
        java.lang.String _buscaTarifaVale_peso = "";
        java.lang.Integer _buscaTarifaVale_codFormato = null;
        java.lang.Double _buscaTarifaVale_comprimento = null;
        java.lang.Double _buscaTarifaVale_altura = null;
        java.lang.Double _buscaTarifaVale_largura = null;
        java.lang.Double _buscaTarifaVale_valorDeclarado = null;
        java.lang.String _buscaTarifaVale_servicoAdicional = "";
        try {
            webService.correios.atende.ValePostal _buscaTarifaVale__return = port.buscaTarifaVale(_buscaTarifaVale_codAdministrativo, _buscaTarifaVale_usuario, _buscaTarifaVale_senha, _buscaTarifaVale_codServico, _buscaTarifaVale_cepOrigem, _buscaTarifaVale_cepDestino, _buscaTarifaVale_peso, _buscaTarifaVale_codFormato, _buscaTarifaVale_comprimento, _buscaTarifaVale_altura, _buscaTarifaVale_largura, _buscaTarifaVale_valorDeclarado, _buscaTarifaVale_servicoAdicional);
            System.out.println("buscaTarifaVale.result=" + _buscaTarifaVale__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validarPostagemSimultanea...");
        java.lang.Integer _validarPostagemSimultanea_codAdministrativo = null;
        java.lang.Integer _validarPostagemSimultanea_codigoServico = null;
        java.lang.String _validarPostagemSimultanea_idCartaoPostagem = "";
        java.lang.String _validarPostagemSimultanea_cepDestinatario = "";
        webService.correios.atende.ColetaSimultanea _validarPostagemSimultanea_coleta = null;
        java.lang.String _validarPostagemSimultanea_usuario = "";
        java.lang.String _validarPostagemSimultanea_senha = "";
        try {
            java.lang.Boolean _validarPostagemSimultanea__return = port.validarPostagemSimultanea(_validarPostagemSimultanea_codAdministrativo, _validarPostagemSimultanea_codigoServico, _validarPostagemSimultanea_idCartaoPostagem, _validarPostagemSimultanea_cepDestinatario, _validarPostagemSimultanea_coleta, _validarPostagemSimultanea_usuario, _validarPostagemSimultanea_senha);
            System.out.println("validarPostagemSimultanea.result=" + _validarPostagemSimultanea__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getStatusPLP...");
        java.util.List<webService.correios.atende.ObjetoPostal> _getStatusPLP_arg0 = null;
        java.lang.String _getStatusPLP_arg1 = "";
        try {
            webService.correios.atende.StatusPlp _getStatusPLP__return = port.getStatusPLP(_getStatusPLP_arg0, _getStatusPLP_arg1);
            System.out.println("getStatusPLP.result=" + _getStatusPLP__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaServicosXServicosAdicionais...");
        java.lang.String _buscaServicosXServicosAdicionais_usuario = "";
        java.lang.String _buscaServicosXServicosAdicionais_senha = "";
        try {
            java.util.List<java.lang.String> _buscaServicosXServicosAdicionais__return = port.buscaServicosXServicosAdicionais(_buscaServicosXServicosAdicionais_usuario, _buscaServicosXServicosAdicionais_senha);
            System.out.println("buscaServicosXServicosAdicionais.result=" + _buscaServicosXServicosAdicionais__return);

        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelarPedidoScol...");
        java.lang.String _cancelarPedidoScol_codAdministrativo = "";
        java.lang.String _cancelarPedidoScol_idPostagem = "";
        java.lang.String _cancelarPedidoScol_tipo = "";
        java.lang.String _cancelarPedidoScol_usuario = "";
        java.lang.String _cancelarPedidoScol_senha = "";
        try {
            webService.correios.atende.RetornoCancelamento _cancelarPedidoScol__return = port.cancelarPedidoScol(_cancelarPedidoScol_codAdministrativo, _cancelarPedidoScol_idPostagem, _cancelarPedidoScol_tipo, _cancelarPedidoScol_usuario, _cancelarPedidoScol_senha);
            System.out.println("cancelarPedidoScol.result=" + _cancelarPedidoScol__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking bloquearObjeto...");
        java.lang.String _bloquearObjeto_numeroEtiqueta = "";
        java.lang.Long _bloquearObjeto_idPlp = null;
        webService.correios.atende.TipoBloqueio _bloquearObjeto_tipoBloqueio = null;
        webService.correios.atende.Acao _bloquearObjeto_acao = null;
        java.lang.String _bloquearObjeto_usuario = "";
        java.lang.String _bloquearObjeto_senha = "";
        try {
            java.lang.String _bloquearObjeto__return = port.bloquearObjeto(_bloquearObjeto_numeroEtiqueta, _bloquearObjeto_idPlp, _bloquearObjeto_tipoBloqueio, _bloquearObjeto_acao, _bloquearObjeto_usuario, _bloquearObjeto_senha);
            System.out.println("bloquearObjeto.result=" + _bloquearObjeto__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaContrato...");
        java.lang.String _buscaContrato_numero = "";
        long _buscaContrato_diretoria = 0;
        java.lang.String _buscaContrato_usuario = "";
        java.lang.String _buscaContrato_senha = "";
        try {
            webService.correios.atende.ContratoERP _buscaContrato__return = port.buscaContrato(_buscaContrato_numero, _buscaContrato_diretoria, _buscaContrato_usuario, _buscaContrato_senha);
            System.out.println("buscaContrato.result=" + _buscaContrato__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaEtiquetas...");
        java.lang.String _solicitaEtiquetas_tipoDestinatario = "";
        java.lang.String _solicitaEtiquetas_identificador = "";
        java.lang.Long _solicitaEtiquetas_idServico = null;
        java.lang.Integer _solicitaEtiquetas_qtdEtiquetas = null;
        java.lang.String _solicitaEtiquetas_usuario = "";
        java.lang.String _solicitaEtiquetas_senha = "";
        try {
            java.lang.String _solicitaEtiquetas__return = port.solicitaEtiquetas(_solicitaEtiquetas_tipoDestinatario, _solicitaEtiquetas_identificador, _solicitaEtiquetas_idServico, _solicitaEtiquetas_qtdEtiquetas, _solicitaEtiquetas_usuario, _solicitaEtiquetas_senha);
            System.out.println("solicitaEtiquetas.result=" + _solicitaEtiquetas__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaXmlPlp...");
        java.lang.Long _solicitaXmlPlp_idPlpMaster = null;
        java.lang.String _solicitaXmlPlp_usuario = "";
        java.lang.String _solicitaXmlPlp_senha = "";
        try {
            java.lang.String _solicitaXmlPlp__return = port.solicitaXmlPlp(_solicitaXmlPlp_idPlpMaster, _solicitaXmlPlp_usuario, _solicitaXmlPlp_senha);
            System.out.println("solicitaXmlPlp.result=" + _solicitaXmlPlp__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validarPostagemReversa...");
        java.lang.String _validarPostagemReversa_codAdministrativo = "";
        java.lang.String _validarPostagemReversa_codigoServico = "";
        java.lang.String _validarPostagemReversa_cepDestinatario = "";
        java.lang.String _validarPostagemReversa_idCartaoPostagem = "";
        webService.correios.atende.ColetaReversa _validarPostagemReversa_coleta = null;
        java.lang.String _validarPostagemReversa_usuario = "";
        java.lang.String _validarPostagemReversa_senha = "";
        try {
            java.lang.Boolean _validarPostagemReversa__return = port.validarPostagemReversa(_validarPostagemReversa_codAdministrativo, _validarPostagemReversa_codigoServico, _validarPostagemReversa_cepDestinatario, _validarPostagemReversa_idCartaoPostagem, _validarPostagemReversa_coleta, _validarPostagemReversa_usuario, _validarPostagemReversa_senha);
            System.out.println("validarPostagemReversa.result=" + _validarPostagemReversa__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaCliente...");
        java.lang.String _buscaCliente_idContrato = "";
        java.lang.String _buscaCliente_idCartaoPostagem = "";
        java.lang.String _buscaCliente_usuario = "";
        java.lang.String _buscaCliente_senha = "";
        try {
            webService.correios.atende.ClienteERP _buscaCliente__return = port.buscaCliente(_buscaCliente_idContrato, _buscaCliente_idCartaoPostagem, _buscaCliente_usuario, _buscaCliente_senha);
            System.out.println("buscaCliente.result=" + _buscaCliente__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaPagamentoEntrega...");
        java.lang.String _buscaPagamentoEntrega_usuario = "";
        java.lang.String _buscaPagamentoEntrega_senha = "";
        java.lang.String _buscaPagamentoEntrega_contrato = "";
        java.lang.String _buscaPagamentoEntrega_dataInicio = "";
        java.lang.String _buscaPagamentoEntrega_dataFim = "";
        java.lang.String _buscaPagamentoEntrega_etiqueta = "";
        try {
            java.lang.String _buscaPagamentoEntrega__return = port.buscaPagamentoEntrega(_buscaPagamentoEntrega_usuario, _buscaPagamentoEntrega_senha, _buscaPagamentoEntrega_contrato, _buscaPagamentoEntrega_dataInicio, _buscaPagamentoEntrega_dataFim, _buscaPagamentoEntrega_etiqueta);
            System.out.println("buscaPagamentoEntrega.result=" + _buscaPagamentoEntrega__return);

        } catch (ErroMontagemRelatorio_Exception e) { 
            System.out.println("Expected exception: ErroMontagemRelatorio has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitarPostagemScol...");
        java.lang.Integer _solicitarPostagemScol_codAdministrativo = null;
        java.lang.String _solicitarPostagemScol_xml = "";
        java.lang.String _solicitarPostagemScol_usuario = "";
        java.lang.String _solicitarPostagemScol_senha = "";
        try {
            java.lang.String _solicitarPostagemScol__return = port.solicitarPostagemScol(_solicitarPostagemScol_codAdministrativo, _solicitarPostagemScol_xml, _solicitarPostagemScol_usuario, _solicitarPostagemScol_senha);
            System.out.println("solicitarPostagemScol.result=" + _solicitarPostagemScol__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaServicos...");
        java.lang.String _buscaServicos_idContrato = "";
        java.lang.String _buscaServicos_idCartaoPostagem = "";
        java.lang.String _buscaServicos_usuario = "";
        java.lang.String _buscaServicos_senha = "";
        try {
            java.util.List<webService.correios.atende.ServicoERP> _buscaServicos__return = port.buscaServicos(_buscaServicos_idContrato, _buscaServicos_idCartaoPostagem, _buscaServicos_usuario, _buscaServicos_senha);
            System.out.println("buscaServicos.result=" + _buscaServicos__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
