
package webService.correios.atende;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-01T20:04:39.964-04:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "AutenticacaoException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class AutenticacaoException extends java.lang.Exception {
    
    private java.lang.String autenticacaoException;

    public AutenticacaoException() {
        super();
    }
    
    public AutenticacaoException(String message) {
        super(message);
    }
    
    public AutenticacaoException(String message, Throwable cause) {
        super(message, cause);
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoException) {
        super(message);
        this.autenticacaoException = autenticacaoException;
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoException, Throwable cause) {
        super(message, cause);
        this.autenticacaoException = autenticacaoException;
    }

    public java.lang.String getFaultInfo() {
        return this.autenticacaoException;
    }
}
