
package webService.correios.atende;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-01T20:04:39.974-04:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "ErroMontagemRelatorio", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class ErroMontagemRelatorio_Exception extends java.lang.Exception {
    
    private webService.correios.atende.ErroMontagemRelatorio erroMontagemRelatorio;

    public ErroMontagemRelatorio_Exception() {
        super();
    }
    
    public ErroMontagemRelatorio_Exception(String message) {
        super(message);
    }
    
    public ErroMontagemRelatorio_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ErroMontagemRelatorio_Exception(String message, webService.correios.atende.ErroMontagemRelatorio erroMontagemRelatorio) {
        super(message);
        this.erroMontagemRelatorio = erroMontagemRelatorio;
    }

    public ErroMontagemRelatorio_Exception(String message, webService.correios.atende.ErroMontagemRelatorio erroMontagemRelatorio, Throwable cause) {
        super(message, cause);
        this.erroMontagemRelatorio = erroMontagemRelatorio;
    }

    public webService.correios.atende.ErroMontagemRelatorio getFaultInfo() {
        return this.erroMontagemRelatorio;
    }
}
