
package webService.correios.atende;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-01T20:04:39.971-04:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class Exception_Exception extends java.lang.Exception {
    
    private webService.correios.atende.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, webService.correios.atende.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, webService.correios.atende.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public webService.correios.atende.Exception getFaultInfo() {
        return this.exception;
    }
}
